/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:ac12b433-db14-42df-9bf0-635d299945de",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_CF304xZeb",
    "aws_user_pools_web_client_id": "5emgpemcc2amvj21d58ovga9nf",
    "oauth": {}
};


export default awsmobile;
